layer:
  raw: spark-warehouse/raw_data
  silver: spark-warehouse/silver_data
  gold: spark-warehouse/gold_data

file:
  result: results/result.txt

url:
  csv_files: https://raw.githubusercontent.com/solytic/opendata/refs/heads/master/bronze/demo/Date%3D2021-11-0

csv:
  suffixes: [
              1/part-00000.csv,
              2/part-00000.csv,
              2/part-00001.csv,
              3/part-00001.csv,
              3/part-00002.csv,
              4/part-00002.csv,
              4/part-00003.csv,
              4/part-00004.csv,
              5/part-00004.csv,
              5/part-00005.csv,
              5/part-00006.csv,
              6/part-00006.csv,
              6/part-00007.csv,
              6/part-00008.csv,
              7/part-00008.csv,
              7/part-00009.csv
            ]